# Note: You must restart bin/shakapacker-dev-server for changes to take effect
# This file contains rspack-specific configuration for shakapacker.

default: &default
  source_path: app/javascript
  source_entry_path: packs
  nested_entries: true
  css_extract_ignore_order_warnings: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  webpack_compile_output: true
  shakapacker_precompile: true

  # Use RSpack as the bundler
  assets_bundler: 'rspack'

  # RSpack works better with SWC transpiler
  javascript_transpiler: 'swc'

  additional_paths: []
  cache_manifest: false
  ensure_consistent_versioning: true
  compiler_strategy: digest
  useContentHash: false

  integrity:
    enabled: false
    hash_functions: ["sha384"]
    cross_origin: "anonymous"

development:
  <<: *default
  compile: true
  compiler_strategy: mtime

  # Reference: https://www.rspack.dev/config/dev-server
  dev_server:
    host: localhost
    port: 3035
    # Hot Module Replacement with RSpack
    hot: true
    # RSpack dev server uses 'hot' instead of 'hmr'
    inline_css: true
    client:
      overlay: true
    compress: true
    allowed_hosts: 'auto'
    pretty: true
    headers:
      'Access-Control-Allow-Origin': '*'
    static:
      watch:
        ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  useContentHash: true
  cache_manifest: true