require_relative "./support/package_json_helpers"
require_relative "./support/html_test_helpers"

# `Kernel#abort` and `Kernel#exit` raise SystemExit, which rspec-support deliberately refuses to
# rescue (it is in `AllExceptionsExceptOnesWeMustNotRescue::AVOID_RESCUING`). One example that
# reaches an aborting code path against a real path — `rakelib/release.rake` is built entirely
# out of `abort` — therefore tears the whole process down mid-run, and the summary RSpec already
# printed still reads "N examples, 0 failures" for whatever happened to run first. A truncated
# run then looks exactly like a passing one, and with `exit 0` it is green down to the exit code.
#
# Two mechanisms below, because neither covers the other's ground:
#
#   1. `around` converts a SystemExit raised *inside an example* into an ordinary failure, so the
#      run continues and the offending example is named. This is the readable half.
#   2. `at_exit` is the backstop for everything an example hook cannot see — a SystemExit while
#      loading a spec file, or from a `before(:suite)`, `before(:context)` or `after(:context)`
#      hook. It refuses to let any of those exit zero.
#
# The backstop asks three independent questions, because each catches a case the others miss:
#
#   * Did anything fail? RSpec's own exit status is computed after the suite runs, so an `exit 0`
#     from an `after(:context)` hook in the last group discards it — every example has already
#     run and reported, failures and all, and the process still exits clean. This is the worst of
#     the three: it does not truncate anything, it silently discards real failures.
#   * Did the suite reach the end? Catches a SystemExit before any example was loaded, where
#     nothing is both loaded and unexecuted for the count check to notice.
#   * Did every loaded example run? `after(:suite)` runs from an `ensure` inside
#     `with_suite_hooks`, so the completion flag is set even when a `before(:suite)` hook exits.
#     Only the counts see that one.
#
# The backstop only ever turns green into red: if the process is already exiting non-zero, the run
# is failing on its own and needs no help, so it stays out of the way (a spec file with a syntax
# error, for instance, already exits non-zero and reports its own error).
#
# Known gap: under `--dry-run` RSpec skips `with_suite_hooks`, so the completion flag never gets
# set and only the other two questions are left. A SystemExit raised while *loading* a spec file
# is invisible to both, so `rspec --dry-run` can still exit zero on a truncated load. Dry runs are
# not a pass/fail gate here (CI runs the suite for real via `rake test`), so this is left as a
# known limitation rather than paid for with a heavier mechanism.
suite_reached_completion = false

# Returns why this run must not be allowed to exit zero, or nil when a clean exit is trustworthy.
untrustworthy_success_reason = lambda do
  reporter = RSpec.world.reporter
  failed = reporter.failed_examples.size

  if failed.positive?
    "#{failed} example(s) failed, but the process was about to exit successfully."
  elsif !(suite_reached_completion || RSpec.configuration.dry_run?)
    "The run never reached the end of the suite, so the reported example count is not the whole suite."
  elsif RSpec.world.example_count != reporter.examples.size
    "Only #{reporter.examples.size} of #{RSpec.world.example_count} loaded examples ran."
  end
rescue StandardError
  # The backstop must never itself be the reason a run breaks; fall back to the weakest signal.
  "The run never reached the end of the suite." unless suite_reached_completion
end

at_exit do
  terminating = $!
  exit_status = if terminating.is_a?(SystemExit)
    terminating.status
  else
    terminating.nil? ? 0 : 1
  end
  next unless exit_status.zero?

  reason = untrustworthy_success_reason.call
  next unless reason

  warn ""
  warn "❌ #{reason}"
  warn "   A `Kernel#abort` or `Kernel#exit` reached while loading a spec file, or from a suite " \
       "or context hook, is the usual cause."
  warn "   Failing the run so it cannot be mistaken for a clean pass."
  exit 1
end

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

  config.include HtmlTestHelpers

  config.after(:suite) { suite_reached_completion = true }

  # Outermost `around` hook, so it wraps every group-level `around` too.
  config.around do |example|
    begin
      example.run
    rescue SystemExit => e
      raise RuntimeError,
            "Example exited the process with SystemExit (status #{e.status}): #{e.message}. " \
            "RSpec does not rescue SystemExit, so without this hook the run would stop here and " \
            "report every earlier example as a passing suite. Stub the aborting call, or assert " \
            "on it with `expect { ... }.to raise_error(SystemExit)`.",
            e.backtrace
    end
  end

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  config.disable_monkey_patching!

  # This setting enables warnings. It's recommended, but in some cases may
  # be too noisy due to issues in dependencies.
  config.warnings = true

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
