#!/usr/bin/env ruby

binary = "npm"
major_version = "9"

unless ENV["SHAKAPACKER_EXPECTED_PACKAGE_MANGER"] == binary
  raise StandardError, "(#{binary}) this is not the package manager you're looking for..."
end

exec({ 
  "NPM_CONFIG_REGISTRY" => "https://registry.yarnpkg.com"
}, "npx", "-y", "#{binary}@#{major_version}", *ARGV)
