#!/usr/bin/env ruby

binary = "pnpm"
major_version = "8"

unless ENV["SHAKAPACKER_EXPECTED_PACKAGE_MANGER"] == binary
  raise StandardError, "(#{binary}) this is not the package manager you're looking for..."
end

exec("npx", "-y", "#{binary}@#{major_version}", *ARGV)
