name: Ruby based checks

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Ruby rubocop
        run: bundle exec rubocop

  test:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.7', '3.0', '3.1', '3.2']
        gemfile:
          - gemfiles/Gemfile-rails.6.0.x
          - gemfiles/Gemfile-rails.6.1.x
          - gemfiles/Gemfile-rails.7.0.x
          - gemfiles/Gemfile-rails.7.1.x
          # Uncomment the following line only to ensure compatibility with the
          # upcomming Rails versions, maybe before a release.
          #- gemfiles/Gemfile-rails-edge
        exclude:
          - ruby: '3.1'
            gemfile: gemfiles/Gemfile-rails.6.0.x
          - ruby: '3.2'
            gemfile: gemfiles/Gemfile-rails.6.0.x

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Ruby specs
        run: bundle exec rake run_spec:gem
        env:
          SHAKAPACKER_USE_PACKAGE_JSON_GEM: "false"

      - name: Ruby specs
        run: bundle exec rake run_spec:gem
        env:
          SHAKAPACKER_USE_PACKAGE_JSON_GEM: "true"
