name: Ruby specs

on: [push, pull_request]

jobs:
  test:
    name: Ruby specs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.6', '2.7', '3.0']
        gemfile:
          - gemfiles/Gemfile-rails.6.0.x
          - gemfiles/Gemfile-rails.6.1.x
          - gemfiles/Gemfile-rails.7.0.x
          # Uncomment the following line only to ensure compatibility with the
          # upcomming Rails versions, maybe before a release.
          #- gemfiles/Gemfile-rails-edge
        exclude:
          - ruby: 2.6
            os: ubuntu-latest
            gemfile: gemfiles/Gemfile-rails.7.0.x
          - ruby: 2.6
            os: ubuntu-latest
            gemfile: gemfiles/Gemfile-rails-edge

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Ruby specs
        run: bundle exec rake run_spec:gem
        env:
          SHAKAPACKER_USE_PACKAGE_JSON_GEM: "false"

      - name: Ruby specs
        run: bundle exec rake run_spec:gem
        env:
          SHAKAPACKER_USE_PACKAGE_JSON_GEM: "true"
